### PR TITLE
Add error message when invalid userid or name is specified when fetch…

### PR DESCRIPTION
**Pull request by austenmc**
…ing a user

### CODE REVIEW

**Comment by Vassyli** [comment]
I think that this is **not** a good idea. I thought about this too, but decided against it. Reporting an invalid user.id or user.name (especially the first) will allow bots to probe the api for valid users.

While this isn't an issue per se (since we are limiting access to query.user anyway to owner only or administrator), I'm still not comfortable with giving unnecessary information to the user. Either you have a valid id/name and are allowed to access that field, or you are not.

**Comment by austenmc** [comment]
I thought about this as well:

1. Usernames are discoverable via login attacks so they are already vulnerable.
2. I dont think keeping id's secret is a sustainable or good plan for security.

However, Im happy to switch this to an error that the user just forgot to include properly formatted arguments, which was the source of some debugging headache for me :)

**Comment by Vassyli** [comment]
1. We should fix this then instead
2. It must not be something we can relay on, true, but do not let us give
out information that we dont intend at that point.

Let us give an argument empty error or something like this instead, yeah.

Am 24.03.2017 19:01 schrieb "Austen McDonald" <notifications@github.com>:

I thought about this as well:

   1. Usernames are discoverable via login attacks so they are already
   vulnerable.
   2. I dont think keeping id's secret is a sustainable or good plan for
   security.

However, Im happy to switch this to an error that the user just forgot to
include properly formatted arguments, which was the source of some
debugging headache for me :)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/lotgd/crate-graphql/pull/35#issuecomment-289100340>,
or mute
the thread

**Comment by Vassyli** [comment]
Can you elaborate on 1? Auth is not telling if username or password is incorrect:

```
        // Do not tell if user is unknown or password wrong
        if ($user === null || $passwordVerified === false) {
            // Throw a UserError - this gets catched by the GraphQL bundle to deliver a
            // valid graphql error.
            throw new UserError("The login credentials are invalid.");
        }
```

The only possibility to get a list of user names is to use mutation.createCharacter.

**Comment by austenmc** [comment]
Sorry, I misspoke. I meant via signup attacks. Presumably users will receive a message like "email/username unavailable" when they attempt to sign up w/ a duplicate name. I dont think its worth bending over backwards to prevent this. Emails are not secrets.

**Comment by Vassyli** [comment]
I agree.

> However, Im happy to switch this to an error that the user just forgot to include properly formatted arguments, which was the source of some debugging headache for me :)

Let's do this.

**Review by Vassyli — CHANGES_REQUESTED** [review]
If the reason you added this check is missing arguments in your side, you should add instead a catch for missing arguments.

**Comment by austenmc** [comment]
@Vassyli can you check this change?

**Review by Vassyli — APPROVED** [review]

**Pull request merged**
